spring.application.name=language-app-backend

#Configure spring to use the .env file
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:mysql://localhost:3306/language_learning_ai?useSSL=false
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create
#create to reset tables on app restart. update to persist data

spring.jpa.show-sql=true
